
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class ActiveSkill : Luban.BeanBase
{
    public ActiveSkill(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadString();
        CoolTime = _buf.ReadFloat();
        MaxSlotNum = _buf.ReadInt();
        PassiveSkill = _buf.ReadInt();
    }

    public static ActiveSkill DeserializeActiveSkill(ByteBuf _buf)
    {
        return new ActiveSkill(_buf);
    }

    /// <summary>
    /// ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 名字
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 冷却时间
    /// </summary>
    public readonly float CoolTime;
    /// <summary>
    /// 存储上限
    /// </summary>
    public readonly int MaxSlotNum;
    /// <summary>
    /// 被动技能
    /// </summary>
    public readonly int PassiveSkill;
   
    public const int __ID__ = 605189835;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "coolTime:" + CoolTime + ","
        + "maxSlotNum:" + MaxSlotNum + ","
        + "passiveSkill:" + PassiveSkill + ","
        + "}";
    }
}

}
