
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.activeSkill
{
public partial class TbActiveSkill
{
    private readonly System.Collections.Generic.Dictionary<int, ActiveSkill> _dataMap;
    private readonly System.Collections.Generic.List<ActiveSkill> _dataList;
    
    public TbActiveSkill(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, ActiveSkill>();
        _dataList = new System.Collections.Generic.List<ActiveSkill>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            ActiveSkill _v;
            _v = ActiveSkill.DeserializeActiveSkill(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, ActiveSkill> DataMap => _dataMap;
    public System.Collections.Generic.List<ActiveSkill> DataList => _dataList;

    public ActiveSkill GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public ActiveSkill Get(int key) => _dataMap[key];
    public ActiveSkill this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}
