
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class ArmorLevelAttribute : Luban.BeanBase
{
    public ArmorLevelAttribute(ByteBuf _buf) 
    {
        Quality = _buf.ReadInt();
        Level = _buf.ReadInt();
        Hp = _buf.ReadFloat();
        Attack = _buf.ReadFloat();
        HpPercentage = _buf.ReadFloat();
        AttackPercentage = _buf.ReadFloat();
        DefensePercentage = _buf.ReadFloat();
        CriticalHitRate = _buf.ReadFloat();
        CriticalHitDamage = _buf.ReadFloat();
        DamageBonus = _buf.ReadFloat();
    }

    public static ArmorLevelAttribute DeserializeArmorLevelAttribute(ByteBuf _buf)
    {
        return new ArmorLevelAttribute(_buf);
    }

    /// <summary>
    /// 品质(联合主键)
    /// </summary>
    public readonly int Quality;
    /// <summary>
    /// 等级(联合主键)
    /// </summary>
    public readonly int Level;
    /// <summary>
    /// 生命值
    /// </summary>
    public readonly float Hp;
    /// <summary>
    /// 攻击
    /// </summary>
    public readonly float Attack;
    /// <summary>
    /// 生命值百分比
    /// </summary>
    public readonly float HpPercentage;
    /// <summary>
    /// 攻击力百分比
    /// </summary>
    public readonly float AttackPercentage;
    /// <summary>
    /// 防御力百分比
    /// </summary>
    public readonly float DefensePercentage;
    /// <summary>
    /// 暴击率
    /// </summary>
    public readonly float CriticalHitRate;
    /// <summary>
    /// 暴击伤害
    /// </summary>
    public readonly float CriticalHitDamage;
    /// <summary>
    /// 伤害加成
    /// </summary>
    public readonly float DamageBonus;
   
    public const int __ID__ = -463651209;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
        
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "quality:" + Quality + ","
        + "level:" + Level + ","
        + "hp:" + Hp + ","
        + "attack:" + Attack + ","
        + "hpPercentage:" + HpPercentage + ","
        + "attackPercentage:" + AttackPercentage + ","
        + "defensePercentage:" + DefensePercentage + ","
        + "criticalHitRate:" + CriticalHitRate + ","
        + "criticalHitDamage:" + CriticalHitDamage + ","
        + "damageBonus:" + DamageBonus + ","
        + "}";
    }
}

}
