
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class ArmorConfig : Luban.BeanBase
{
    public ArmorConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadString();
        Type = (ArmorType)_buf.ReadInt();
        Quality = _buf.ReadInt();
        Icon = _buf.ReadString();
        SecondaryAttributeBonusType = (AttributeBonusType)_buf.ReadInt();
        PassiveSkill = _buf.ReadInt();
    }

    public static ArmorConfig DeserializeArmorConfig(ByteBuf _buf)
    {
        return new ArmorConfig(_buf);
    }

    /// <summary>
    /// ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 名字
    /// </summary>
    public readonly string Name;
    public readonly ArmorType Type;
    /// <summary>
    /// 品质(1-5)
    /// </summary>
    public readonly int Quality;
    public readonly string Icon;
    public readonly AttributeBonusType SecondaryAttributeBonusType;
    public readonly int PassiveSkill;
   
    public const int __ID__ = -910799551;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "type:" + Type + ","
        + "quality:" + Quality + ","
        + "icon:" + Icon + ","
        + "secondaryAttributeBonusType:" + SecondaryAttributeBonusType + ","
        + "passiveSkill:" + PassiveSkill + ","
        + "}";
    }
}

}
