
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    public enum ArmorType
    {
        /// <summary>
        /// 头部，头盔
        /// </summary>
        Head = 0,
        /// <summary>
        /// 胸部，上衣
        /// </summary>
        Chest = 1,
        /// <summary>
        /// 腰部，腰带
        /// </summary>
        Waist = 2,
        /// <summary>
        /// 腿部，下装
        /// </summary>
        Legs = 3,
        /// <summary>
        /// 脚部，鞋子
        /// </summary>
        Feet = 4,
    }

} 

