
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.artifact
{
public partial class TbArtifact
{
    private readonly System.Collections.Generic.Dictionary<int, ArtifactConfig> _dataMap;
    private readonly System.Collections.Generic.List<ArtifactConfig> _dataList;
    
    public TbArtifact(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, ArtifactConfig>();
        _dataList = new System.Collections.Generic.List<ArtifactConfig>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            ArtifactConfig _v;
            _v = ArtifactConfig.DeserializeArtifactConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, ArtifactConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<ArtifactConfig> DataList => _dataList;

    public ArtifactConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public ArtifactConfig Get(int key) => _dataMap[key];
    public ArtifactConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}
