
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    public enum AttributeBonusType
    {
        /// <summary>
        /// 百分比生命值
        /// </summary>
        Hp = 0,
        /// <summary>
        /// 百分比攻击力
        /// </summary>
        Attack = 1,
        /// <summary>
        /// 百分比防御力
        /// </summary>
        Defense = 2,
        /// <summary>
        /// 暴击率
        /// </summary>
        CriticalHitRate = 3,
        /// <summary>
        /// 暴击伤害
        /// </summary>
        CriticalHitDamage = 4,
        /// <summary>
        /// 伤害加成
        /// </summary>
        DamageBonus = 5,
    }

} 

