
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class BlessingConfig : Luban.BeanBase
{
    public BlessingConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadString();
        Quality = _buf.ReadInt();
        PassiveSkillId = _buf.ReadInt();
        Describe = _buf.ReadString();
    }

    public static BlessingConfig DeserializeBlessingConfig(ByteBuf _buf)
    {
        return new BlessingConfig(_buf);
    }

    /// <summary>
    /// Id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 名字
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 品质(1-3)
    /// </summary>
    public readonly int Quality;
    public readonly int PassiveSkillId;
    /// <summary>
    /// 祝福描述
    /// </summary>
    public readonly string Describe;
   
    public const int __ID__ = -1218565303;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "quality:" + Quality + ","
        + "passiveSkillId:" + PassiveSkillId + ","
        + "describe:" + Describe + ","
        + "}";
    }
}

}
