
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.blessing
{
public partial class TbBlessing
{
    private readonly System.Collections.Generic.Dictionary<int, BlessingConfig> _dataMap;
    private readonly System.Collections.Generic.List<BlessingConfig> _dataList;
    
    public TbBlessing(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, BlessingConfig>();
        _dataList = new System.Collections.Generic.List<BlessingConfig>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            BlessingConfig _v;
            _v = BlessingConfig.DeserializeBlessingConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, BlessingConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<BlessingConfig> DataList => _dataList;

    public BlessingConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public BlessingConfig Get(int key) => _dataMap[key];
    public BlessingConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}
