
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.bufferNumerical
{
public partial class TbBufferNumerical
{
    private readonly System.Collections.Generic.List<BufferNumerical> _dataList;

    private System.Collections.Generic.Dictionary<(int, int), BufferNumerical> _dataMapUnion;

    public TbBufferNumerical(ByteBuf _buf)
    {
        _dataList = new System.Collections.Generic.List<BufferNumerical>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            BufferNumerical _v;
            _v = BufferNumerical.DeserializeBufferNumerical(_buf);
            _dataList.Add(_v);
        }
        _dataMapUnion = new System.Collections.Generic.Dictionary<(int, int), BufferNumerical>();
        foreach(var _v in _dataList)
        {
            _dataMapUnion.Add((_v.BufferId, _v.Level), _v);
        }
    }

    public System.Collections.Generic.List<BufferNumerical> DataList => _dataList;

    public BufferNumerical Get(int bufferId, int level) => _dataMapUnion.TryGetValue((bufferId, level), out BufferNumerical __v) ? __v : null;
    
    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }
}

}
