
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class CharacterConfig : Luban.BeanBase
{
    public CharacterConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadString();
        Quality = _buf.ReadInt();
        CharacterAssetName = _buf.ReadString();
        ContainerAssetName = _buf.ReadString();
        CanReceiveKnockUp = _buf.ReadBool();
        NormalSkill = _buf.ReadInt();
        SpSkill = _buf.ReadInt();
        PassiveSkill1 = _buf.ReadInt();
        PassiveSkill2 = _buf.ReadInt();
        AscensionAttributeBonusType = (AttributeBonusType)_buf.ReadInt();
    }

    public static CharacterConfig DeserializeCharacterConfig(ByteBuf _buf)
    {
        return new CharacterConfig(_buf);
    }

    /// <summary>
    /// ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 名字
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 品质
    /// </summary>
    public readonly int Quality;
    public readonly string CharacterAssetName;
    public readonly string ContainerAssetName;
    public readonly bool CanReceiveKnockUp;
    public readonly int NormalSkill;
    public readonly int SpSkill;
    public readonly int PassiveSkill1;
    public readonly int PassiveSkill2;
    /// <summary>
    /// 突破属性加成类型
    /// </summary>
    public readonly AttributeBonusType AscensionAttributeBonusType;
   
    public const int __ID__ = 676994987;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
        
        
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "quality:" + Quality + ","
        + "characterAssetName:" + CharacterAssetName + ","
        + "containerAssetName:" + ContainerAssetName + ","
        + "canReceiveKnockUp:" + CanReceiveKnockUp + ","
        + "normalSkill:" + NormalSkill + ","
        + "spSkill:" + SpSkill + ","
        + "passiveSkill1:" + PassiveSkill1 + ","
        + "passiveSkill2:" + PassiveSkill2 + ","
        + "ascensionAttributeBonusType:" + AscensionAttributeBonusType + ","
        + "}";
    }
}

}
