
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class CharacterBaseAttribute : Luban.BeanBase
{
    public CharacterBaseAttribute(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Hp = _buf.ReadFloat();
        Attack = _buf.ReadFloat();
        Defense = _buf.ReadFloat();
    }

    public static CharacterBaseAttribute DeserializeCharacterBaseAttribute(ByteBuf _buf)
    {
        return new CharacterBaseAttribute(_buf);
    }

    /// <summary>
    /// ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 基础血量
    /// </summary>
    public readonly float Hp;
    /// <summary>
    /// 基础攻击
    /// </summary>
    public readonly float Attack;
    /// <summary>
    /// 基础防御
    /// </summary>
    public readonly float Defense;
   
    public const int __ID__ = -1128191422;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "hp:" + Hp + ","
        + "attack:" + Attack + ","
        + "defense:" + Defense + ","
        + "}";
    }
}

}
