
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class CharacterLevelExp : Luban.BeanBase
{
    public CharacterLevelExp(ByteBuf _buf) 
    {
        Level = _buf.ReadInt();
        UpExp = _buf.ReadInt();
        TotalExp = _buf.ReadInt();
    }

    public static CharacterLevelExp DeserializeCharacterLevelExp(ByteBuf _buf)
    {
        return new CharacterLevelExp(_buf);
    }

    /// <summary>
    /// ID
    /// </summary>
    public readonly int Level;
    public readonly int UpExp;
    public readonly int TotalExp;
   
    public const int __ID__ = 500612642;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "level:" + Level + ","
        + "upExp:" + UpExp + ","
        + "totalExp:" + TotalExp + ","
        + "}";
    }
}

}
