
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.characterAscensionBonus
{
public partial class TbCharacterAscensionBonus
{
    private readonly System.Collections.Generic.Dictionary<AttributeBonusType, CharacterAscensionBonus> _dataMap;
    private readonly System.Collections.Generic.List<CharacterAscensionBonus> _dataList;
    
    public TbCharacterAscensionBonus(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<AttributeBonusType, CharacterAscensionBonus>();
        _dataList = new System.Collections.Generic.List<CharacterAscensionBonus>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            CharacterAscensionBonus _v;
            _v = CharacterAscensionBonus.DeserializeCharacterAscensionBonus(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<AttributeBonusType, CharacterAscensionBonus> DataMap => _dataMap;
    public System.Collections.Generic.List<CharacterAscensionBonus> DataList => _dataList;

    public CharacterAscensionBonus GetOrDefault(AttributeBonusType key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public CharacterAscensionBonus Get(AttributeBonusType key) => _dataMap[key];
    public CharacterAscensionBonus this[AttributeBonusType key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}
