
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class CharacterAscensionAttribute : Luban.BeanBase
{
    public CharacterAscensionAttribute(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Hp = _buf.ReadFloat();
        Attack = _buf.ReadFloat();
        Defense = _buf.ReadFloat();
    }

    public static CharacterAscensionAttribute DeserializeCharacterAscensionAttribute(ByteBuf _buf)
    {
        return new CharacterAscensionAttribute(_buf);
    }

    /// <summary>
    /// ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 突破加成总生命值(1-6突破比例=&gt;38:27:36:27:27:27)
    /// </summary>
    public readonly float Hp;
    /// <summary>
    /// 突破加成总攻击力
    /// </summary>
    public readonly float Attack;
    /// <summary>
    /// 突破加成总防御力
    /// </summary>
    public readonly float Defense;
   
    public const int __ID__ = 223654326;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "hp:" + Hp + ","
        + "attack:" + Attack + ","
        + "defense:" + Defense + ","
        + "}";
    }
}

}
