
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.characterLevelMultiplier
{
public partial class TbCharacterLevelMultiplier
{
    private readonly System.Collections.Generic.Dictionary<int, CharacterLevelMultiplier> _dataMap;
    private readonly System.Collections.Generic.List<CharacterLevelMultiplier> _dataList;
    
    public TbCharacterLevelMultiplier(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, CharacterLevelMultiplier>();
        _dataList = new System.Collections.Generic.List<CharacterLevelMultiplier>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            CharacterLevelMultiplier _v;
            _v = CharacterLevelMultiplier.DeserializeCharacterLevelMultiplier(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, CharacterLevelMultiplier> DataMap => _dataMap;
    public System.Collections.Generic.List<CharacterLevelMultiplier> DataList => _dataList;

    public CharacterLevelMultiplier GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public CharacterLevelMultiplier Get(int key) => _dataMap[key];
    public CharacterLevelMultiplier this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}
