
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class CharacterAscensionBonus : Luban.BeanBase
{
    public CharacterAscensionBonus(ByteBuf _buf) 
    {
        Id = (AttributeBonusType)_buf.ReadInt();
        BonusA = _buf.ReadFloat();
        BonusB = _buf.ReadFloat();
    }

    public static CharacterAscensionBonus DeserializeCharacterAscensionBonus(ByteBuf _buf)
    {
        return new CharacterAscensionBonus(_buf);
    }

    /// <summary>
    /// Type
    /// </summary>
    public readonly AttributeBonusType Id;
    /// <summary>
    /// 4星基础加成
    /// </summary>
    public readonly float BonusA;
    /// <summary>
    /// 5星 基础加成
    /// </summary>
    public readonly float BonusB;
   
    public const int __ID__ = -1851145159;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "bonusA:" + BonusA + ","
        + "bonusB:" + BonusB + ","
        + "}";
    }
}

}
