
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.characterBaseAttribute
{
public partial class TbCharacterBaseAttribute
{
    private readonly System.Collections.Generic.Dictionary<int, CharacterBaseAttribute> _dataMap;
    private readonly System.Collections.Generic.List<CharacterBaseAttribute> _dataList;
    
    public TbCharacterBaseAttribute(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, CharacterBaseAttribute>();
        _dataList = new System.Collections.Generic.List<CharacterBaseAttribute>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            CharacterBaseAttribute _v;
            _v = CharacterBaseAttribute.DeserializeCharacterBaseAttribute(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, CharacterBaseAttribute> DataMap => _dataMap;
    public System.Collections.Generic.List<CharacterBaseAttribute> DataList => _dataList;

    public CharacterBaseAttribute GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public CharacterBaseAttribute Get(int key) => _dataMap[key];
    public CharacterBaseAttribute this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}
