
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.characterAscensionAttribute
{
public partial class TbCharacterAscensionAttribute
{
    private readonly System.Collections.Generic.Dictionary<int, CharacterAscensionAttribute> _dataMap;
    private readonly System.Collections.Generic.List<CharacterAscensionAttribute> _dataList;
    
    public TbCharacterAscensionAttribute(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, CharacterAscensionAttribute>();
        _dataList = new System.Collections.Generic.List<CharacterAscensionAttribute>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            CharacterAscensionAttribute _v;
            _v = CharacterAscensionAttribute.DeserializeCharacterAscensionAttribute(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, CharacterAscensionAttribute> DataMap => _dataMap;
    public System.Collections.Generic.List<CharacterAscensionAttribute> DataList => _dataList;

    public CharacterAscensionAttribute GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public CharacterAscensionAttribute Get(int key) => _dataMap[key];
    public CharacterAscensionAttribute this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}
