
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class ChestConfig : Luban.BeanBase
{
    public ChestConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Quality = _buf.ReadInt();
        {int __n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);Rewards = new RewardConfig[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { RewardConfig __e0;__e0 = RewardConfig.DeserializeRewardConfig(_buf); Rewards[__index0] = __e0;}}
    }

    public static ChestConfig DeserializeChestConfig(ByteBuf _buf)
    {
        return new ChestConfig(_buf);
    }

    /// <summary>
    /// ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 品质(1-4)
    /// </summary>
    public readonly int Quality;
    public readonly RewardConfig[] Rewards;
   
    public const int __ID__ = -808519293;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "quality:" + Quality + ","
        + "rewards:" + Luban.StringUtil.CollectionToString(Rewards) + ","
        + "}";
    }
}

}
