
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.dialogueCheck
{
public partial class TbDialogueCheck
{
    private readonly System.Collections.Generic.Dictionary<int, DialogueCheck> _dataMap;
    private readonly System.Collections.Generic.List<DialogueCheck> _dataList;
    
    public TbDialogueCheck(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, DialogueCheck>();
        _dataList = new System.Collections.Generic.List<DialogueCheck>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            DialogueCheck _v;
            _v = DialogueCheck.DeserializeDialogueCheck(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, DialogueCheck> DataMap => _dataMap;
    public System.Collections.Generic.List<DialogueCheck> DataList => _dataList;

    public DialogueCheck GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public DialogueCheck Get(int key) => _dataMap[key];
    public DialogueCheck this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}
