
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class DialogueCheck : Luban.BeanBase
{
    public DialogueCheck(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        CheckType = _buf.ReadInt();
        CheckValue = _buf.ReadInt();
    }

    public static DialogueCheck DeserializeDialogueCheck(ByteBuf _buf)
    {
        return new DialogueCheck(_buf);
    }

    public readonly int Id;
    /// <summary>
    /// Check类型
    /// </summary>
    public readonly int CheckType;
    /// <summary>
    /// Check值
    /// </summary>
    public readonly int CheckValue;
   
    public const int __ID__ = -284773904;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "checkType:" + CheckType + ","
        + "checkValue:" + CheckValue + ","
        + "}";
    }
}

}
