
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.dialogueTrigger
{
public partial class TbDialogueTrigger
{
    private readonly System.Collections.Generic.Dictionary<int, DialogueTrigger> _dataMap;
    private readonly System.Collections.Generic.List<DialogueTrigger> _dataList;
    
    public TbDialogueTrigger(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, DialogueTrigger>();
        _dataList = new System.Collections.Generic.List<DialogueTrigger>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            DialogueTrigger _v;
            _v = DialogueTrigger.DeserializeDialogueTrigger(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, DialogueTrigger> DataMap => _dataMap;
    public System.Collections.Generic.List<DialogueTrigger> DataList => _dataList;

    public DialogueTrigger GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public DialogueTrigger Get(int key) => _dataMap[key];
    public DialogueTrigger this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}
