
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class EnemyLevelMultiplier : Luban.BeanBase
{
    public EnemyLevelMultiplier(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        MultiplierHPA = _buf.ReadFloat();
        MultiplierHPB = _buf.ReadFloat();
        MultiplierATKA = _buf.ReadFloat();
        MultiplierATKB = _buf.ReadFloat();
    }

    public static EnemyLevelMultiplier DeserializeEnemyLevelMultiplier(ByteBuf _buf)
    {
        return new EnemyLevelMultiplier(_buf);
    }

    /// <summary>
    /// Level
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 生命值成长系数A(适配角色突破的属性曲线)
    /// </summary>
    public readonly float MultiplierHPA;
    /// <summary>
    /// 生命值成长系数B(R方 = 0.9999)
    /// </summary>
    public readonly float MultiplierHPB;
    /// <summary>
    /// 攻击力成长系数A(曲线)
    /// </summary>
    public readonly float MultiplierATKA;
    /// <summary>
    /// 攻击力成长系数B(曲线 与A相比 41-84 攻击力系数降低了 )
    /// </summary>
    public readonly float MultiplierATKB;
   
    public const int __ID__ = -1485014051;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "multiplierHPA:" + MultiplierHPA + ","
        + "multiplierHPB:" + MultiplierHPB + ","
        + "multiplierATKA:" + MultiplierATKA + ","
        + "multiplierATKB:" + MultiplierATKB + ","
        + "}";
    }
}

}
