
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class EnemyConfig : Luban.BeanBase
{
    public EnemyConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadString();
        CharacterAssetName = _buf.ReadString();
        ContainerAssetName = _buf.ReadString();
        CanReceiveKnockUp = _buf.ReadBool();
        AiAssetName = _buf.ReadString();
        PassiveSkill = _buf.ReadInt();
        BaseAttributeId = _buf.ReadInt();
    }

    public static EnemyConfig DeserializeEnemyConfig(ByteBuf _buf)
    {
        return new EnemyConfig(_buf);
    }

    /// <summary>
    /// ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 名字
    /// </summary>
    public readonly string Name;
    public readonly string CharacterAssetName;
    public readonly string ContainerAssetName;
    public readonly bool CanReceiveKnockUp;
    public readonly string AiAssetName;
    public readonly int PassiveSkill;
    public readonly int BaseAttributeId;
   
    public const int __ID__ = 1284055242;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "characterAssetName:" + CharacterAssetName + ","
        + "containerAssetName:" + ContainerAssetName + ","
        + "canReceiveKnockUp:" + CanReceiveKnockUp + ","
        + "aiAssetName:" + AiAssetName + ","
        + "passiveSkill:" + PassiveSkill + ","
        + "baseAttributeId:" + BaseAttributeId + ","
        + "}";
    }
}

}
