
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.enemyLevelMultiplier
{
public partial class TbEnemyLevelMultiplier
{
    private readonly System.Collections.Generic.Dictionary<int, EnemyLevelMultiplier> _dataMap;
    private readonly System.Collections.Generic.List<EnemyLevelMultiplier> _dataList;
    
    public TbEnemyLevelMultiplier(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, EnemyLevelMultiplier>();
        _dataList = new System.Collections.Generic.List<EnemyLevelMultiplier>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            EnemyLevelMultiplier _v;
            _v = EnemyLevelMultiplier.DeserializeEnemyLevelMultiplier(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, EnemyLevelMultiplier> DataMap => _dataMap;
    public System.Collections.Generic.List<EnemyLevelMultiplier> DataList => _dataList;

    public EnemyLevelMultiplier GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public EnemyLevelMultiplier Get(int key) => _dataMap[key];
    public EnemyLevelMultiplier this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}
