
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class ItemConfig : Luban.BeanBase
{
    public ItemConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadString();
        Type = (ItemType)_buf.ReadInt();
        Quality = _buf.ReadInt();
        Icon = _buf.ReadString();
    }

    public static ItemConfig DeserializeItemConfig(ByteBuf _buf)
    {
        return new ItemConfig(_buf);
    }

    /// <summary>
    /// ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 名字
    /// </summary>
    public readonly string Name;
    public readonly ItemType Type;
    /// <summary>
    /// 品质(1-5)
    /// </summary>
    public readonly int Quality;
    /// <summary>
    /// UI_ItemIcon_{}
    /// </summary>
    public readonly string Icon;
   
    public const int __ID__ = -764023723;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "type:" + Type + ","
        + "quality:" + Quality + ","
        + "icon:" + Icon + ","
        + "}";
    }
}

}
