
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class Localization : Luban.BeanBase
{
    public Localization(ByteBuf _buf) 
    {
        Key = _buf.ReadString();
        Cn = _buf.ReadString();
        En = _buf.ReadString();
    }

    public static Localization DeserializeLocalization(ByteBuf _buf)
    {
        return new Localization(_buf);
    }

    /// <summary>
    /// 本地化key
    /// </summary>
    public readonly string Key;
    public readonly string Cn;
    public readonly string En;
   
    public const int __ID__ = -647685447;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "key:" + Key + ","
        + "cn:" + Cn + ","
        + "en:" + En + ","
        + "}";
    }
}

}
