
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.localization
{
public partial class TbLocalization
{
    private readonly System.Collections.Generic.Dictionary<string, Localization> _dataMap;
    private readonly System.Collections.Generic.List<Localization> _dataList;
    
    public TbLocalization(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<string, Localization>();
        _dataList = new System.Collections.Generic.List<Localization>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            Localization _v;
            _v = Localization.DeserializeLocalization(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Key, _v);
        }
    }

    public System.Collections.Generic.Dictionary<string, Localization> DataMap => _dataMap;
    public System.Collections.Generic.List<Localization> DataList => _dataList;

    public Localization GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Localization Get(string key) => _dataMap[key];
    public Localization this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}
