
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.npc
{
public partial class TbNpc
{
    private readonly System.Collections.Generic.Dictionary<int, NpcConfig> _dataMap;
    private readonly System.Collections.Generic.List<NpcConfig> _dataList;
    
    public TbNpc(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, NpcConfig>();
        _dataList = new System.Collections.Generic.List<NpcConfig>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            NpcConfig _v;
            _v = NpcConfig.DeserializeNpcConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, NpcConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<NpcConfig> DataList => _dataList;

    public NpcConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public NpcConfig Get(int key) => _dataMap[key];
    public NpcConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}
