
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class NpcConfig : Luban.BeanBase
{
    public NpcConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadString();
        CharacterAssetName = _buf.ReadString();
        ContainerAssetName = _buf.ReadString();
        AiAssetName = _buf.ReadString();
    }

    public static NpcConfig DeserializeNpcConfig(ByteBuf _buf)
    {
        return new NpcConfig(_buf);
    }

    /// <summary>
    /// ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 名字
    /// </summary>
    public readonly string Name;
    public readonly string CharacterAssetName;
    public readonly string ContainerAssetName;
    public readonly string AiAssetName;
   
    public const int __ID__ = -1928671901;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "characterAssetName:" + CharacterAssetName + ","
        + "containerAssetName:" + ContainerAssetName + ","
        + "aiAssetName:" + AiAssetName + ","
        + "}";
    }
}

}
