
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public partial struct RewardConfig
{
    public RewardConfig(ByteBuf _buf) 
    {
        Type = (RewardType)_buf.ReadInt();
        Id = _buf.ReadInt();
        Value = _buf.ReadInt();
    }

    public static RewardConfig DeserializeRewardConfig(ByteBuf _buf)
    {
        return new RewardConfig(_buf);
    }

    /// <summary>
    /// 道具类型
    /// </summary>
    public readonly RewardType Type;
    /// <summary>
    /// Id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 数量
    /// </summary>
    public readonly int Value;
   

    public  void ResolveRef(Tables tables)
    {
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "Type:" + Type + ","
        + "Id:" + Id + ","
        + "Value:" + Value + ","
        + "}";
    }
}

}
