
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    public enum RewardType
    {
        /// <summary>
        /// 道具
        /// </summary>
        Item = 0,
        /// <summary>
        /// 武器
        /// </summary>
        Weapon = 1,
        /// <summary>
        /// 防具
        /// </summary>
        Armor = 2,
        /// <summary>
        /// 金币
        /// </summary>
        Coin = 3,
    }

} 

