
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.room
{
public partial class TbRoom
{
    private readonly System.Collections.Generic.Dictionary<int, RoomConfig> _dataMap;
    private readonly System.Collections.Generic.List<RoomConfig> _dataList;
    
    public TbRoom(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, RoomConfig>();
        _dataList = new System.Collections.Generic.List<RoomConfig>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            RoomConfig _v;
            _v = RoomConfig.DeserializeRoomConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, RoomConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<RoomConfig> DataList => _dataList;

    public RoomConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public RoomConfig Get(int key) => _dataMap[key];
    public RoomConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}
