
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    public enum RoomType
    {
        Init = 0,
        Random = 1,
        Heal = 2,
        Shop = 3,
        Upgrade = 4,
        ProMiniBoss = 5,
        MiniBoss = 6,
        ProBoss = 7,
        Boss = 8,
        Combat = 9,
    }

} 

