
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class RoomConfig : Luban.BeanBase
{
    public RoomConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadString();
        Type = (RoomType)_buf.ReadInt();
        AssetName = _buf.ReadString();
        Priority = _buf.ReadInt();
        Probability = _buf.ReadInt();
        StartNum = _buf.ReadInt();
        IntervalNum = _buf.ReadInt();
        IsInevitable = _buf.ReadBool();
    }

    public static RoomConfig DeserializeRoomConfig(ByteBuf _buf)
    {
        return new RoomConfig(_buf);
    }

    /// <summary>
    /// 祝福Id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 名字
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 类型
    /// </summary>
    public readonly RoomType Type;
    /// <summary>
    /// 资源名
    /// </summary>
    public readonly string AssetName;
    /// <summary>
    /// 优先级
    /// </summary>
    public readonly int Priority;
    /// <summary>
    /// 概率
    /// </summary>
    public readonly int Probability;
    public readonly int StartNum;
    public readonly int IntervalNum;
    public readonly bool IsInevitable;
   
    public const int __ID__ = -1837073379;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "type:" + Type + ","
        + "assetName:" + AssetName + ","
        + "priority:" + Priority + ","
        + "probability:" + Probability + ","
        + "startNum:" + StartNum + ","
        + "intervalNum:" + IntervalNum + ","
        + "isInevitable:" + IsInevitable + ","
        + "}";
    }
}

}
