
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.summoner
{
public partial class TbSummoner
{
    private readonly System.Collections.Generic.Dictionary<int, SummonerConfig> _dataMap;
    private readonly System.Collections.Generic.List<SummonerConfig> _dataList;
    
    public TbSummoner(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, SummonerConfig>();
        _dataList = new System.Collections.Generic.List<SummonerConfig>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            SummonerConfig _v;
            _v = SummonerConfig.DeserializeSummonerConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, SummonerConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<SummonerConfig> DataList => _dataList;

    public SummonerConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public SummonerConfig Get(int key) => _dataMap[key];
    public SummonerConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}
