
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class SummonerConfig : Luban.BeanBase
{
    public SummonerConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadString();
        Quality = _buf.ReadInt();
        CharacterAssetName = _buf.ReadString();
        ContainerAssetName = _buf.ReadString();
        CanReceiveKnockUp = _buf.ReadBool();
        AiAssetName = _buf.ReadString();
    }

    public static SummonerConfig DeserializeSummonerConfig(ByteBuf _buf)
    {
        return new SummonerConfig(_buf);
    }

    /// <summary>
    /// ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 名字
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 品质
    /// </summary>
    public readonly int Quality;
    public readonly string CharacterAssetName;
    public readonly string ContainerAssetName;
    public readonly bool CanReceiveKnockUp;
    public readonly string AiAssetName;
   
    public const int __ID__ = -1928388016;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "quality:" + Quality + ","
        + "characterAssetName:" + CharacterAssetName + ","
        + "containerAssetName:" + ContainerAssetName + ","
        + "canReceiveKnockUp:" + CanReceiveKnockUp + ","
        + "aiAssetName:" + AiAssetName + ","
        + "}";
    }
}

}
