
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace cfg
{
public partial class Tables
{
    public blessing.TbBlessing TbBlessing {get; }
    public artifact.TbArtifact TbArtifact {get; }
    public localization.TbLocalization TbLocalization {get; }
    public dialogueActor.TbDialogueActor TbDialogueActor {get; }
    public dialogueTrigger.TbDialogueTrigger TbDialogueTrigger {get; }
    public dialogueCheck.TbDialogueCheck TbDialogueCheck {get; }
    public character.TbCharacter TbCharacter {get; }
    public characterBaseAttribute.TbCharacterBaseAttribute TbCharacterBaseAttribute {get; }
    public characterAscensionAttribute.TbCharacterAscensionAttribute TbCharacterAscensionAttribute {get; }
    public characterLevelMultiplier.TbCharacterLevelMultiplier TbCharacterLevelMultiplier {get; }
    public characterAscensionBonus.TbCharacterAscensionBonus TbCharacterAscensionBonus {get; }
    public characterLevelExp.TbCharacterLevelExp TbCharacterLevelExp {get; }
    public enemy.TbEnemy TbEnemy {get; }
    public enemyBaseAttribute.TbEnemyBaseAttribute TbEnemyBaseAttribute {get; }
    public enemyLevelMultiplier.TbEnemyLevelMultiplier TbEnemyLevelMultiplier {get; }
    public weapon.TbWeapon TbWeapon {get; }
    public weaponLevelMultiplier.TbWeaponLevelMultiplier TbWeaponLevelMultiplier {get; }
    public weaponAscensionAttribute.TbWeaponAscensionAttribute TbWeaponAscensionAttribute {get; }
    public weaponSecondaryAttributeLevelMultiplier.TbWeaponSecondaryAttributeLevelMultiplier TbWeaponSecondaryAttributeLevelMultiplier {get; }
    public bufferNumerical.TbBufferNumerical TbBufferNumerical {get; }
    public activeSkill.TbActiveSkill TbActiveSkill {get; }
    public room.TbRoom TbRoom {get; }
    public armor.TbArmor TbArmor {get; }
    public armorLevelAttribute.TbArmorLevelAttribute TbArmorLevelAttribute {get; }
    public item.TbItem TbItem {get; }
    public chest.TbChest TbChest {get; }
    public summoner.TbSummoner TbSummoner {get; }
    public npc.TbNpc TbNpc {get; }

    public Tables(System.Func<string, ByteBuf> loader)
    {
        TbBlessing = new blessing.TbBlessing(loader("blessing_tbblessing"));
        TbArtifact = new artifact.TbArtifact(loader("artifact_tbartifact"));
        TbLocalization = new localization.TbLocalization(loader("localization_tblocalization"));
        TbDialogueActor = new dialogueActor.TbDialogueActor(loader("dialogueactor_tbdialogueactor"));
        TbDialogueTrigger = new dialogueTrigger.TbDialogueTrigger(loader("dialoguetrigger_tbdialoguetrigger"));
        TbDialogueCheck = new dialogueCheck.TbDialogueCheck(loader("dialoguecheck_tbdialoguecheck"));
        TbCharacter = new character.TbCharacter(loader("character_tbcharacter"));
        TbCharacterBaseAttribute = new characterBaseAttribute.TbCharacterBaseAttribute(loader("characterbaseattribute_tbcharacterbaseattribute"));
        TbCharacterAscensionAttribute = new characterAscensionAttribute.TbCharacterAscensionAttribute(loader("characterascensionattribute_tbcharacterascensionattribute"));
        TbCharacterLevelMultiplier = new characterLevelMultiplier.TbCharacterLevelMultiplier(loader("characterlevelmultiplier_tbcharacterlevelmultiplier"));
        TbCharacterAscensionBonus = new characterAscensionBonus.TbCharacterAscensionBonus(loader("characterascensionbonus_tbcharacterascensionbonus"));
        TbCharacterLevelExp = new characterLevelExp.TbCharacterLevelExp(loader("characterlevelexp_tbcharacterlevelexp"));
        TbEnemy = new enemy.TbEnemy(loader("enemy_tbenemy"));
        TbEnemyBaseAttribute = new enemyBaseAttribute.TbEnemyBaseAttribute(loader("enemybaseattribute_tbenemybaseattribute"));
        TbEnemyLevelMultiplier = new enemyLevelMultiplier.TbEnemyLevelMultiplier(loader("enemylevelmultiplier_tbenemylevelmultiplier"));
        TbWeapon = new weapon.TbWeapon(loader("weapon_tbweapon"));
        TbWeaponLevelMultiplier = new weaponLevelMultiplier.TbWeaponLevelMultiplier(loader("weaponlevelmultiplier_tbweaponlevelmultiplier"));
        TbWeaponAscensionAttribute = new weaponAscensionAttribute.TbWeaponAscensionAttribute(loader("weaponascensionattribute_tbweaponascensionattribute"));
        TbWeaponSecondaryAttributeLevelMultiplier = new weaponSecondaryAttributeLevelMultiplier.TbWeaponSecondaryAttributeLevelMultiplier(loader("weaponsecondaryattributelevelmultiplier_tbweaponsecondaryattributelevelmultiplier"));
        TbBufferNumerical = new bufferNumerical.TbBufferNumerical(loader("buffernumerical_tbbuffernumerical"));
        TbActiveSkill = new activeSkill.TbActiveSkill(loader("activeskill_tbactiveskill"));
        TbRoom = new room.TbRoom(loader("room_tbroom"));
        TbArmor = new armor.TbArmor(loader("armor_tbarmor"));
        TbArmorLevelAttribute = new armorLevelAttribute.TbArmorLevelAttribute(loader("armorlevelattribute_tbarmorlevelattribute"));
        TbItem = new item.TbItem(loader("item_tbitem"));
        TbChest = new chest.TbChest(loader("chest_tbchest"));
        TbSummoner = new summoner.TbSummoner(loader("summoner_tbsummoner"));
        TbNpc = new npc.TbNpc(loader("npc_tbnpc"));
        ResolveRef();
    }
	
    public Tables(System.Collections.Generic.Dictionary<string,ByteBuf> byteBufs)
    {
        TbBlessing = new blessing.TbBlessing(byteBufs["blessing_tbblessing"]);
        TbArtifact = new artifact.TbArtifact(byteBufs["artifact_tbartifact"]);
        TbLocalization = new localization.TbLocalization(byteBufs["localization_tblocalization"]);
        TbDialogueActor = new dialogueActor.TbDialogueActor(byteBufs["dialogueactor_tbdialogueactor"]);
        TbDialogueTrigger = new dialogueTrigger.TbDialogueTrigger(byteBufs["dialoguetrigger_tbdialoguetrigger"]);
        TbDialogueCheck = new dialogueCheck.TbDialogueCheck(byteBufs["dialoguecheck_tbdialoguecheck"]);
        TbCharacter = new character.TbCharacter(byteBufs["character_tbcharacter"]);
        TbCharacterBaseAttribute = new characterBaseAttribute.TbCharacterBaseAttribute(byteBufs["characterbaseattribute_tbcharacterbaseattribute"]);
        TbCharacterAscensionAttribute = new characterAscensionAttribute.TbCharacterAscensionAttribute(byteBufs["characterascensionattribute_tbcharacterascensionattribute"]);
        TbCharacterLevelMultiplier = new characterLevelMultiplier.TbCharacterLevelMultiplier(byteBufs["characterlevelmultiplier_tbcharacterlevelmultiplier"]);
        TbCharacterAscensionBonus = new characterAscensionBonus.TbCharacterAscensionBonus(byteBufs["characterascensionbonus_tbcharacterascensionbonus"]);
        TbCharacterLevelExp = new characterLevelExp.TbCharacterLevelExp(byteBufs["characterlevelexp_tbcharacterlevelexp"]);
        TbEnemy = new enemy.TbEnemy(byteBufs["enemy_tbenemy"]);
        TbEnemyBaseAttribute = new enemyBaseAttribute.TbEnemyBaseAttribute(byteBufs["enemybaseattribute_tbenemybaseattribute"]);
        TbEnemyLevelMultiplier = new enemyLevelMultiplier.TbEnemyLevelMultiplier(byteBufs["enemylevelmultiplier_tbenemylevelmultiplier"]);
        TbWeapon = new weapon.TbWeapon(byteBufs["weapon_tbweapon"]);
        TbWeaponLevelMultiplier = new weaponLevelMultiplier.TbWeaponLevelMultiplier(byteBufs["weaponlevelmultiplier_tbweaponlevelmultiplier"]);
        TbWeaponAscensionAttribute = new weaponAscensionAttribute.TbWeaponAscensionAttribute(byteBufs["weaponascensionattribute_tbweaponascensionattribute"]);
        TbWeaponSecondaryAttributeLevelMultiplier = new weaponSecondaryAttributeLevelMultiplier.TbWeaponSecondaryAttributeLevelMultiplier(byteBufs["weaponsecondaryattributelevelmultiplier_tbweaponsecondaryattributelevelmultiplier"]);
        TbBufferNumerical = new bufferNumerical.TbBufferNumerical(byteBufs["buffernumerical_tbbuffernumerical"]);
        TbActiveSkill = new activeSkill.TbActiveSkill(byteBufs["activeskill_tbactiveskill"]);
        TbRoom = new room.TbRoom(byteBufs["room_tbroom"]);
        TbArmor = new armor.TbArmor(byteBufs["armor_tbarmor"]);
        TbArmorLevelAttribute = new armorLevelAttribute.TbArmorLevelAttribute(byteBufs["armorlevelattribute_tbarmorlevelattribute"]);
        TbItem = new item.TbItem(byteBufs["item_tbitem"]);
        TbChest = new chest.TbChest(byteBufs["chest_tbchest"]);
        TbSummoner = new summoner.TbSummoner(byteBufs["summoner_tbsummoner"]);
        TbNpc = new npc.TbNpc(byteBufs["npc_tbnpc"]);
        ResolveRef();
    }
	
	public static string[] GetFiles()
    {
        return new string[]
        {
			"blessing_tbblessing",
			"artifact_tbartifact",
			"localization_tblocalization",
			"dialogueactor_tbdialogueactor",
			"dialoguetrigger_tbdialoguetrigger",
			"dialoguecheck_tbdialoguecheck",
			"character_tbcharacter",
			"characterbaseattribute_tbcharacterbaseattribute",
			"characterascensionattribute_tbcharacterascensionattribute",
			"characterlevelmultiplier_tbcharacterlevelmultiplier",
			"characterascensionbonus_tbcharacterascensionbonus",
			"characterlevelexp_tbcharacterlevelexp",
			"enemy_tbenemy",
			"enemybaseattribute_tbenemybaseattribute",
			"enemylevelmultiplier_tbenemylevelmultiplier",
			"weapon_tbweapon",
			"weaponlevelmultiplier_tbweaponlevelmultiplier",
			"weaponascensionattribute_tbweaponascensionattribute",
			"weaponsecondaryattributelevelmultiplier_tbweaponsecondaryattributelevelmultiplier",
			"buffernumerical_tbbuffernumerical",
			"activeskill_tbactiveskill",
			"room_tbroom",
			"armor_tbarmor",
			"armorlevelattribute_tbarmorlevelattribute",
			"item_tbitem",
			"chest_tbchest",
			"summoner_tbsummoner",
			"npc_tbnpc",
        };
    }
    
    private void ResolveRef()
    {
        TbBlessing.ResolveRef(this);
        TbArtifact.ResolveRef(this);
        TbLocalization.ResolveRef(this);
        TbDialogueActor.ResolveRef(this);
        TbDialogueTrigger.ResolveRef(this);
        TbDialogueCheck.ResolveRef(this);
        TbCharacter.ResolveRef(this);
        TbCharacterBaseAttribute.ResolveRef(this);
        TbCharacterAscensionAttribute.ResolveRef(this);
        TbCharacterLevelMultiplier.ResolveRef(this);
        TbCharacterAscensionBonus.ResolveRef(this);
        TbCharacterLevelExp.ResolveRef(this);
        TbEnemy.ResolveRef(this);
        TbEnemyBaseAttribute.ResolveRef(this);
        TbEnemyLevelMultiplier.ResolveRef(this);
        TbWeapon.ResolveRef(this);
        TbWeaponLevelMultiplier.ResolveRef(this);
        TbWeaponAscensionAttribute.ResolveRef(this);
        TbWeaponSecondaryAttributeLevelMultiplier.ResolveRef(this);
        TbBufferNumerical.ResolveRef(this);
        TbActiveSkill.ResolveRef(this);
        TbRoom.ResolveRef(this);
        TbArmor.ResolveRef(this);
        TbArmorLevelAttribute.ResolveRef(this);
        TbItem.ResolveRef(this);
        TbChest.ResolveRef(this);
        TbSummoner.ResolveRef(this);
        TbNpc.ResolveRef(this);
    }
}

}
