
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.weaponLevelMultiplier
{
public partial class TbWeaponLevelMultiplier
{
    private readonly System.Collections.Generic.Dictionary<int, WeaponLevelMultiplier> _dataMap;
    private readonly System.Collections.Generic.List<WeaponLevelMultiplier> _dataList;
    
    public TbWeaponLevelMultiplier(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, WeaponLevelMultiplier>();
        _dataList = new System.Collections.Generic.List<WeaponLevelMultiplier>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            WeaponLevelMultiplier _v;
            _v = WeaponLevelMultiplier.DeserializeWeaponLevelMultiplier(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, WeaponLevelMultiplier> DataMap => _dataMap;
    public System.Collections.Generic.List<WeaponLevelMultiplier> DataList => _dataList;

    public WeaponLevelMultiplier GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public WeaponLevelMultiplier Get(int key) => _dataMap[key];
    public WeaponLevelMultiplier this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}
