
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.weaponSecondaryAttributeLevelMultiplier
{
public partial class TbWeaponSecondaryAttributeLevelMultiplier
{
    private readonly System.Collections.Generic.Dictionary<int, WeaponSecondaryAttributeLevelMultiplier> _dataMap;
    private readonly System.Collections.Generic.List<WeaponSecondaryAttributeLevelMultiplier> _dataList;
    
    public TbWeaponSecondaryAttributeLevelMultiplier(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, WeaponSecondaryAttributeLevelMultiplier>();
        _dataList = new System.Collections.Generic.List<WeaponSecondaryAttributeLevelMultiplier>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            WeaponSecondaryAttributeLevelMultiplier _v;
            _v = WeaponSecondaryAttributeLevelMultiplier.DeserializeWeaponSecondaryAttributeLevelMultiplier(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Level, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, WeaponSecondaryAttributeLevelMultiplier> DataMap => _dataMap;
    public System.Collections.Generic.List<WeaponSecondaryAttributeLevelMultiplier> DataList => _dataList;

    public WeaponSecondaryAttributeLevelMultiplier GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public WeaponSecondaryAttributeLevelMultiplier Get(int key) => _dataMap[key];
    public WeaponSecondaryAttributeLevelMultiplier this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}
