
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class WeaponSecondaryAttributeLevelMultiplier : Luban.BeanBase
{
    public WeaponSecondaryAttributeLevelMultiplier(ByteBuf _buf) 
    {
        Level = _buf.ReadInt();
        Multiplier = _buf.ReadFloat();
    }

    public static WeaponSecondaryAttributeLevelMultiplier DeserializeWeaponSecondaryAttributeLevelMultiplier(ByteBuf _buf)
    {
        return new WeaponSecondaryAttributeLevelMultiplier(_buf);
    }

    /// <summary>
    /// 等级
    /// </summary>
    public readonly int Level;
    /// <summary>
    /// 系数
    /// </summary>
    public readonly float Multiplier;
   
    public const int __ID__ = 1060005089;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "level:" + Level + ","
        + "multiplier:" + Multiplier + ","
        + "}";
    }
}

}
