
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class WeaponLevelMultiplier : Luban.BeanBase
{
    public WeaponLevelMultiplier(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        MultiplierA1 = _buf.ReadFloat();
        MultiplierA2 = _buf.ReadFloat();
        MultiplierA3 = _buf.ReadFloat();
        MultiplierB1 = _buf.ReadFloat();
        MultiplierB2 = _buf.ReadFloat();
        MultiplierB3 = _buf.ReadFloat();
        MultiplierB4 = _buf.ReadFloat();
        MultiplierC1 = _buf.ReadFloat();
        MultiplierC2 = _buf.ReadFloat();
        MultiplierC3 = _buf.ReadFloat();
        MultiplierC4 = _buf.ReadFloat();
    }

    public static WeaponLevelMultiplier DeserializeWeaponLevelMultiplier(ByteBuf _buf)
    {
        return new WeaponLevelMultiplier(_buf);
    }

    /// <summary>
    /// Level
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 1-3 星 成长系数1
    /// </summary>
    public readonly float MultiplierA1;
    /// <summary>
    /// 1-3 星 成长系数2
    /// </summary>
    public readonly float MultiplierA2;
    /// <summary>
    /// 1-3 星 成长系数3
    /// </summary>
    public readonly float MultiplierA3;
    /// <summary>
    /// 4 星 成长系数1
    /// </summary>
    public readonly float MultiplierB1;
    /// <summary>
    /// 4 星 成长系数2
    /// </summary>
    public readonly float MultiplierB2;
    /// <summary>
    /// 4 星 成长系数3
    /// </summary>
    public readonly float MultiplierB3;
    /// <summary>
    /// 4 星 成长系数4
    /// </summary>
    public readonly float MultiplierB4;
    /// <summary>
    /// 5 星 成长系数1
    /// </summary>
    public readonly float MultiplierC1;
    /// <summary>
    /// 5 星 成长系数2
    /// </summary>
    public readonly float MultiplierC2;
    /// <summary>
    /// 5 星 成长系数3
    /// </summary>
    public readonly float MultiplierC3;
    /// <summary>
    /// 5 星 成长系数4
    /// </summary>
    public readonly float MultiplierC4;
   
    public const int __ID__ = -731927927;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
        
        
        
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "multiplierA1:" + MultiplierA1 + ","
        + "multiplierA2:" + MultiplierA2 + ","
        + "multiplierA3:" + MultiplierA3 + ","
        + "multiplierB1:" + MultiplierB1 + ","
        + "multiplierB2:" + MultiplierB2 + ","
        + "multiplierB3:" + MultiplierB3 + ","
        + "multiplierB4:" + MultiplierB4 + ","
        + "multiplierC1:" + MultiplierC1 + ","
        + "multiplierC2:" + MultiplierC2 + ","
        + "multiplierC3:" + MultiplierC3 + ","
        + "multiplierC4:" + MultiplierC4 + ","
        + "}";
    }
}

}
