
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.weaponAscensionAttribute
{
public partial class TbWeaponAscensionAttribute
{
    private readonly System.Collections.Generic.Dictionary<int, WeaponAscensionAttribute> _dataMap;
    private readonly System.Collections.Generic.List<WeaponAscensionAttribute> _dataList;
    
    public TbWeaponAscensionAttribute(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, WeaponAscensionAttribute>();
        _dataList = new System.Collections.Generic.List<WeaponAscensionAttribute>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            WeaponAscensionAttribute _v;
            _v = WeaponAscensionAttribute.DeserializeWeaponAscensionAttribute(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Quality, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, WeaponAscensionAttribute> DataMap => _dataMap;
    public System.Collections.Generic.List<WeaponAscensionAttribute> DataList => _dataList;

    public WeaponAscensionAttribute GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public WeaponAscensionAttribute Get(int key) => _dataMap[key];
    public WeaponAscensionAttribute this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}
