
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    public enum WeaponType
    {
        /// <summary>
        /// 剑
        /// </summary>
        Sword = 0,
        /// <summary>
        /// 弓
        /// </summary>
        Bow = 1,
        /// <summary>
        /// 长枪
        /// </summary>
        Spear = 2,
        /// <summary>
        /// 魔杖
        /// </summary>
        MagicWand = 3,
    }

} 

