
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class WeaponConfig : Luban.BeanBase
{
    public WeaponConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadString();
        Type = (WeaponType)_buf.ReadInt();
        Quality = _buf.ReadInt();
        Icon = _buf.ReadString();
        Attack = _buf.ReadFloat();
        SecondaryAttributeBonusType = (AttributeBonusType)_buf.ReadInt();
        SecondaryAttributeBonusValue = _buf.ReadFloat();
        PassiveSkill = _buf.ReadInt();
    }

    public static WeaponConfig DeserializeWeaponConfig(ByteBuf _buf)
    {
        return new WeaponConfig(_buf);
    }

    /// <summary>
    /// ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 名字
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 武器类型
    /// </summary>
    public readonly WeaponType Type;
    /// <summary>
    /// 品质(1-5)
    /// </summary>
    public readonly int Quality;
    /// <summary>
    /// UI_EquipIcon_{}
    /// </summary>
    public readonly string Icon;
    /// <summary>
    /// 基础攻击力
    /// </summary>
    public readonly float Attack;
    public readonly AttributeBonusType SecondaryAttributeBonusType;
    public readonly float SecondaryAttributeBonusValue;
    /// <summary>
    /// 被动技能
    /// </summary>
    public readonly int PassiveSkill;
   
    public const int __ID__ = 127041694;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "type:" + Type + ","
        + "quality:" + Quality + ","
        + "icon:" + Icon + ","
        + "attack:" + Attack + ","
        + "secondaryAttributeBonusType:" + SecondaryAttributeBonusType + ","
        + "secondaryAttributeBonusValue:" + SecondaryAttributeBonusValue + ","
        + "passiveSkill:" + PassiveSkill + ","
        + "}";
    }
}

}
