
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class WeaponAscensionAttribute : Luban.BeanBase
{
    public WeaponAscensionAttribute(ByteBuf _buf) 
    {
        Quality = _buf.ReadInt();
        Ascension1 = _buf.ReadFloat();
        Ascension2 = _buf.ReadFloat();
        Ascension3 = _buf.ReadFloat();
        Ascension4 = _buf.ReadFloat();
        Ascension5 = _buf.ReadFloat();
        Ascension6 = _buf.ReadFloat();
    }

    public static WeaponAscensionAttribute DeserializeWeaponAscensionAttribute(ByteBuf _buf)
    {
        return new WeaponAscensionAttribute(_buf);
    }

    /// <summary>
    /// 品质
    /// </summary>
    public readonly int Quality;
    /// <summary>
    /// 突破1
    /// </summary>
    public readonly float Ascension1;
    /// <summary>
    /// 突破2
    /// </summary>
    public readonly float Ascension2;
    /// <summary>
    /// 突破3
    /// </summary>
    public readonly float Ascension3;
    /// <summary>
    /// 突破4
    /// </summary>
    public readonly float Ascension4;
    /// <summary>
    /// 突破5
    /// </summary>
    public readonly float Ascension5;
    /// <summary>
    /// 突破6
    /// </summary>
    public readonly float Ascension6;
   
    public const int __ID__ = 1633435177;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "quality:" + Quality + ","
        + "ascension1:" + Ascension1 + ","
        + "ascension2:" + Ascension2 + ","
        + "ascension3:" + Ascension3 + ","
        + "ascension4:" + Ascension4 + ","
        + "ascension5:" + Ascension5 + ","
        + "ascension6:" + Ascension6 + ","
        + "}";
    }
}

}
