
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.weapon
{
public partial class TbWeapon
{
    private readonly System.Collections.Generic.Dictionary<int, WeaponConfig> _dataMap;
    private readonly System.Collections.Generic.List<WeaponConfig> _dataList;
    
    public TbWeapon(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, WeaponConfig>();
        _dataList = new System.Collections.Generic.List<WeaponConfig>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            WeaponConfig _v;
            _v = WeaponConfig.DeserializeWeaponConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, WeaponConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<WeaponConfig> DataList => _dataList;

    public WeaponConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public WeaponConfig Get(int key) => _dataMap[key];
    public WeaponConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}
